version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: firndebi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports: ["5440:5432"]
  backend:
    image: python:3.12-slim
    volumes: [".:/app"]
    working_dir: /app/backend
    command: ["python", "manage.py"]
    depends_on: [db]
  frontend:
    image: node:18-alpine
    volumes: [".:/app"]
    working_dir: /app/frontend
    command: ["npm", "run", "build"]
