name: e2e
on:
  workflow_dispatch:
jobs:
  cypress:
    runs-on: ubuntu-latest
    container: cypress/included:13.7.0
    steps:
      - uses: actions/checkout@v4
      - run: npm ci --prefix frontend
      - run: npx cypress run || echo "E2E placeholders"
